name: Release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  lint-clang:
    name: Run Clang lint
    uses: kuba2k2/kuba2k2/.github/workflows/lint-clang.yml@master
  build-pio:
    name: Build PlatformIO project
    needs:
      - lint-clang
    uses: kuba2k2/kuba2k2/.github/workflows/build-pio.yml@master
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-24.04-arm
            pio-env: linux_aarch64
            post-build: |
              cd .pio/build/linux_aarch64/
              cp firefox-webserial firefox-webserial-linux-aarch64
            output-bin: firefox-webserial-linux-aarch64
            output-artifact: firefox-webserial-native-linux-aarch64
    with:
      runs-on: ${{ matrix.os.runs-on }}
      project-directory: ./native/
      args: -e ${{ matrix.os.pio-env }}
      post-build: ${{ matrix.os.post-build }}
      files: |
        native/.pio/build/${{ matrix.os.pio-env }}/${{ matrix.os.output-bin }}
      output-artifact: ${{ matrix.os.output-artifact }}

  release:
    name: Publish GitHub release
    runs-on: ubuntu-latest
    needs:
      - build-pio
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: firefox-webserial-native-*
          path: dist
          merge-multiple: true

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/firefox-webserial-*
          fail_on_unmatched_files: true
          generate_release_notes: true
